version: '2'
services:
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  postgres:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tapajos
    volumes:
    - postgres-data:/var/lib/postgresql

volumes:
  mysql-data:
    driver: local
  postgres-data:
    driver: local
