version: '2'
services:
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
